"""Prospect company jobs enums (Schema doc §6.16-6.23, §6.27-6.28)."""

from services.common.enums import (
    EMPLOYMENT_TYPES, JOB_BOARDS, JOB_BOARD_POSTING_STATUSES,
    JOB_CANDIDATE_MATCH_METHODS, JOB_CANDIDATE_STATUSES, JOB_CONFIDENTIALITY,
    JOB_PAID_STATUSES, JOB_SENIORITY, JOB_SOURCES, JOB_STATUSES,
    get_label, get_value, reverse,
)

JOB_SENIORITY_REVERSE = reverse(JOB_SENIORITY)
EMPLOYMENT_TYPES_REVERSE = reverse(EMPLOYMENT_TYPES)
JOB_PAID_STATUSES_REVERSE = reverse(JOB_PAID_STATUSES)
JOB_CONFIDENTIALITY_REVERSE = reverse(JOB_CONFIDENTIALITY)
JOB_SOURCES_REVERSE = reverse(JOB_SOURCES)
JOB_STATUSES_REVERSE = reverse(JOB_STATUSES)
JOB_CANDIDATE_MATCH_METHODS_REVERSE = reverse(JOB_CANDIDATE_MATCH_METHODS)
JOB_CANDIDATE_STATUSES_REVERSE = reverse(JOB_CANDIDATE_STATUSES)
JOB_BOARDS_REVERSE = reverse(JOB_BOARDS)
JOB_BOARD_POSTING_STATUSES_REVERSE = reverse(JOB_BOARD_POSTING_STATUSES)

__all__ = [
    "JOB_SENIORITY", "JOB_SENIORITY_REVERSE",
    "EMPLOYMENT_TYPES", "EMPLOYMENT_TYPES_REVERSE",
    "JOB_PAID_STATUSES", "JOB_PAID_STATUSES_REVERSE",
    "JOB_CONFIDENTIALITY", "JOB_CONFIDENTIALITY_REVERSE",
    "JOB_SOURCES", "JOB_SOURCES_REVERSE",
    "JOB_STATUSES", "JOB_STATUSES_REVERSE",
    "JOB_CANDIDATE_MATCH_METHODS", "JOB_CANDIDATE_MATCH_METHODS_REVERSE",
    "JOB_CANDIDATE_STATUSES", "JOB_CANDIDATE_STATUSES_REVERSE",
    "JOB_BOARDS", "JOB_BOARDS_REVERSE",
    "JOB_BOARD_POSTING_STATUSES", "JOB_BOARD_POSTING_STATUSES_REVERSE",
    "get_label", "get_value",
]
