"""Campaigns-relevant enums."""

from services.common.enums import (
    CAMPAIGN_EVENT_TYPES,
    CAMPAIGN_PROSPECT_STATUSES,
    CAMPAIGN_STATUSES,
    CHANNELS,
    get_label,
    get_value,
    reverse,
)

CAMPAIGN_STATUSES_REVERSE = reverse(CAMPAIGN_STATUSES)
CAMPAIGN_PROSPECT_STATUSES_REVERSE = reverse(CAMPAIGN_PROSPECT_STATUSES)
CAMPAIGN_EVENT_TYPES_REVERSE = reverse(CAMPAIGN_EVENT_TYPES)
CHANNELS_REVERSE = reverse(CHANNELS)

__all__ = [
    "CAMPAIGN_STATUSES", "CAMPAIGN_STATUSES_REVERSE",
    "CAMPAIGN_PROSPECT_STATUSES", "CAMPAIGN_PROSPECT_STATUSES_REVERSE",
    "CAMPAIGN_EVENT_TYPES", "CAMPAIGN_EVENT_TYPES_REVERSE",
    "CHANNELS", "CHANNELS_REVERSE",
    "get_label", "get_value",
]
